#!/bin/bash

# Schedule the regular 'brew update' with the following line (i.e. everyday at 9:23h, 15:23h and 21:23h):
#   crontab -l | { cat; echo "23 9,15,21 * * * $(pwd)/zsh/brew_update_job"; } | crontab -
# You might see a dialog to confirm that Terminal.app might update the settings of your computer.
# Also you might have to allow cron to access your disk. See links below.
# SOURCE: 11oct2021 https://serverfault.com/a/1012212
# SOURCE: 11oct2021 https://stackoverflow.com/a/879022
# SOURCE: 11oct2021 https://osxdaily.com/2020/04/27/fix-cron-permissions-macos-full-disk-access/

set -euo pipefail

CACHE_BREW_DIR=~/.cache/brew

mkdir -p "${CACHE_BREW_DIR}"

cat << EOF >> "${CACHE_BREW_DIR}"/update_$(date +"%Y%m_%b").log
---
$(date)

# brew update
$(/usr/local/bin/brew update 2>&1)

# brew outdated
$(/usr/local/bin/brew outdated --verbose 2>&1)

EOF

/usr/local/bin/brew outdated --verbose > "${CACHE_BREW_DIR}"/outdated
