#!/bin/bash

set -euo pipefail

CACHE_BREW_DIR=~/.cache/brew

mkdir -p "${CACHE_BREW_DIR}"

cat << EOF >> "${CACHE_BREW_DIR}"/update_$(date +"%Y%m_%b").log
---
$(date)

# brew update
$(/usr/local/bin/brew update 2>&1)

# brew outdated
$(/usr/local/bin/brew outdated --verbose 2>&1)

EOF

/usr/local/bin/brew outdated --verbose > "${CACHE_BREW_DIR}"/outdated
